### PR TITLE
Update Braid and remove deprecated components from template

### PR DESCRIPTION
**Pull request by tadhglewis**
https://github.com/seek-oss/sku/issues/594

### CODE REVIEW

**Comment by tadhglewis** [comment]
@markdalgleish thanks for adding that. i had a bit of a look and that should be all that's required for updating braid.

I was having trouble running unit tests and had a fair amount failing. Seems like there are a lot of flaky tests? any tips?

**Comment by jahredhope** [comment]
There is one known flakey test. But only one and only in CI, the one that tests the `init` script. Which is my bad, something about CI doesn't like spawning and writing to STIDIN.

If you are seeing flakey tests failing outside of the `init` script that's curious.
I wouldn't expect any others to be flakey. We'll pull it down the branch today and see whats going on.

**Review by mattcompiles — APPROVED** [review]
Thanks for the PR 🍻

**Comment by tadhglewis** [comment]
@mattcompiles @markdalgleish thanks for finishing that one off

**Pull request merged**
